### PR TITLE
Property regex support in PropertyRule

### PR DESCRIPTION
**Pull request by kuboluch**
I needed to create property rule that would include all properties with defined suffix (".version") in automatic conflict resolvement. So i added support for regular expression in PropertyRule. Maybe you would be interested in merging it to your project.

### CODE REVIEW

**Comment by cecom** [comment]
I think this is a nice feature. I had a quick look at the code, the regexp is only matching properties in the global section of the pom, right? I think the profile properties should be also "adjusted" !?!

**Comment by kuboluch** [comment]
True, I hadn't noticed that. I'll get it fixed.

**Comment by kuboluch** [comment]
Ok, i think it's fixed.

**Comment by cecom** [comment]
Ok looks good. It is merged and released. Have a nice Weekend :-)

**Comment by kuboluch** [comment]
Thanks for quick reaction. Have a nice day :)

**Pull request merged**
